server:
  port: 8091
spring:
  application:
    name: activiti
  resources:
        static-locations: classpath:/static/,classpath:/public/,classpath:/templates/
  thymeleaf: 
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  cloud:
    zookeeper:
      connect-string: 140.143.35.107:2181
  datasource:
    name: test
    url: jdbc:mysql://cdb-o742k9kc.bj.tencentcdb.com:10035/daily?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mapper321
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: non-null
#  activiti:
#    process-definition-location-prefix: /
mybatis:
  mapper-locations: classpath*:com/mapper/*/*/data/*.map.xml
  typeAliasesPackage: com.mapper.*.*.data
security:
  basic:
    enabled: false
#logging:
#  level:
#    root: debug
#  file: welcome.log 